#!/bin/bash
# Compares two AGs based on the nodes they have (presumably, AGs generated by the original and modified algorithms respectively).
# The computed statistics are (when running in normal mode, i.e. with no options):
#   - Nodes found by both algorithms
#   - Nodes found only by the original algorithm
#   - Nodes found only by the modified algorithm
# If running in quiet mode (i.e. option -q , inspired by the "quick diff"), the script:
#   - Prints that the graphs are different if at least one node has been found by only one of the algorithms (exit code 1)
#   - Prints nothing if there are no nodes found by only one of the algorithms (exit code 0)
#
# Note: The comparison is purely based on the nodes of the graphs (their names, to be precise).
#       If two nodes with the same name are present in different places in the AGs (e.g at the beginning and end of a path),
#         they are still considered the same.
#       The 'ID' can be removed from the node name using the -i option (it might be different for original and modified graphs
#         even if the states are the same).
#
# NB! This script is based on .dot files, which are by default deleted during the execution of SAGE.
#      To prevent the deletion, use the --keep-files option when running SAGE.

set -euo pipefail
IFS=$'\n\t'

umask 077

usage() {
    echo -e "Usage: $0 [-i] [-q] originalAG.dot modifiedAG.dot\n\n\t-i\tremove node IDs when comparing the attack graphs\n\t-q\treport only when attack graphs differ (do not print differences)"
}

mode="normal"
keep_ids="true"
if [[ $# -ge 2 ]] && [[ $# -le 4 ]]; then
    num_options=0
    while getopts "qi" option; do
        case ${option} in
            q ) mode="quiet" ; num_options=$((num_options + 1)) ;;
            i ) keep_ids="false" ; num_options=$((num_options + 1)) ;;  # Sort of "insensitive [to IDs]"
            \? ) { usage >&2; exit 1; } ;;
        esac
    done

    pos_original=$((1 + num_options))
    pos_modified=$((2 + num_options))
    original="${@:pos_original:1}"
    modified="${@:pos_modified:1}"
# The number of arguments can only be two, three or four
else
    usage >&2
    exit 1
fi

# Check if all input directories exist and that both files have .dot extension
! [[ -f "$original" ]] && { echo "$0: file $original does not exist" >&2 ; exit 1 ; }
! [[ -f "$modified" ]] && { echo "$0: file $modified does not exist" >&2 ; exit 1 ; }
! [[ "${original##*.}" == "dot" ]] && { echo "$0: file $original is not a .dot file" >&2 ; exit 1 ; }
! [[ "${modified##*.}" == "dot" ]] && { echo "$0: file $modified is not a .dot file" >&2 ; exit 1 ; }

# Get the nodes generated by the original and modified algorithms (format: mcat|mserv ; for root node, victim IP is prepended to the name)
if [[ "$keep_ids" == "false" ]]; then
    nodes_original=$(gvpr 'N { print(gsub(gsub($.name, "\r"), "\n", "|")) }' "$original" | sed 's/ | ID: .*//g' | sed 's/^Victim: //' | sort)
    nodes_modified=$(gvpr 'N { print(gsub(gsub($.name, "\r"), "\n", "|")) }' "$modified" | sed 's/ | ID: .*//g' | sed 's/^Victim: //' | sort)
# Use these variables if you also want to compare IDs (i.e. do not remove IDs from the nodes)
else
    nodes_original=$(gvpr 'N { print(gsub(gsub($.name, "\r"), "\n", "|")) }' "$original" | sed 's/^Victim: //' | sort)
    nodes_modified=$(gvpr 'N { print(gsub(gsub($.name, "\r"), "\n", "|")) }' "$modified" | sed 's/^Victim: //' | sort)
fi

# Find the nodes that are common and nodes that are present in only one of the graphs
only_original=$(comm -23 <(echo -e "$nodes_original") <(echo -e "$nodes_modified"))
only_modified=$(comm -13 <(echo -e "$nodes_original") <(echo -e "$nodes_modified"))
common=$(comm -12 <(echo -e "$nodes_original") <(echo -e "$nodes_modified"))

# When running in quiet mode, report if the graphs are different or exit quietly if they are the same
if [[ "$mode" == "quiet" ]]; then
    if [[ -z "$only_original" ]] && [[ -z $only_modified ]]; then
        exit 0;
    else
        echo "Attack graphs $original and $modified are different"
        exit 1
    fi
fi

# When running in normal mode, show the common nodes and nodes that are present in only one of the graphs (and their counts)
# Common nodes (i.e. present in both graphs)
echo "Nodes found by both algorithms: $(echo -e "$common" | sed '/^\s*$/d' | wc -l)"
! [[ -z "$common" ]] && echo -e "$common"
echo -ne "\n"

# Nodes only present in the original graph
if ! [[ -z "$only_original" ]]; then
    echo "Nodes found only by original algorithm: $(echo -e "$only_original" | wc -l)"
    echo -e "$only_original"
else
    echo "Nodes found only by original algorithm: 0"
fi

# Nodes only present in the modified graph
if ! [[ -z "$only_modified" ]]; then
    echo -ne "\n"
    echo "Nodes found only by modified algorithm: $(echo -e "$only_modified" | wc -l)"
    echo -e "$only_modified"
else
    echo "Nodes found only by modified algorithm: 0"
fi

