#!/bin/bash
# Compares two AGs based on the nodes and edges that they have (presumably, AGs generated by the original and modified algorithms respectively).
#
# If two .dot files with AGs are provided, then they are compared with each other.
#   - If running in quiet mode (i.e. option -q , inspired by the "quick diff"), the script:
#       - Prints that the graphs are different if at least one node or edge has been found by only one of the algorithms (exit code 1)
#       - Prints nothing if there are no nodes or edges found by only one of the algorithms (exit code 0)
#   - If running in normal mode (i.e. with no options), then stats generated by `diff-nodes.sh` and `diff-edges.sh` are printed.
# If two directories are provided, then every pair of corresponding AGs is compared against each other (recursively).
#   - The AGs that are different are reported.
#   - To count the number of different AGs in the input directories, pipe the output to `wc` command (e.g. `./diff-ags.sh orig-2017AGs/ merged-sinks-2017AGs/ | wc -l`).
#   - NB! Only the AGs present in both directories are compared. The ones that are present only in one of the directories are ignored.
#
# Note: The comparison is purely based on the node and edges of the graphs (their names and labels, to be precise).
#       See also comments for `diff-nodes.sh` and `diff-edges.sh`.
#
# NB! This script assumes that the directory with the AGs has the name ExpNameAGs/ and that the AG files also have ExpName in their name (i.e. the name has not been changed).
#     To avoid potential errors, please only use alphanumeric characters in the name of the experiments (i.e. no whitespaces, enters etc.).
#
# NB! This script is based on .dot files, which are by default deleted during the execution of SAGE.
#      To prevent the deletion, use the --keep-files option when running SAGE.

set -euo pipefail
IFS=$'\n\t'

umask 077

usage() {
    echo -e "Usage: $0 [-i] [-q] originalAG.dot modifiedAG.dot\n       $0 [-i] originalAGs/ modifiedAGs/\n
        -i\tremove node IDs when comparing the attack graphs
        -q\treport only when attack graphs differ (do not print differences; no effect when comparing directories with the attack graphs)"
}

mode="normal"
keep_ids="true"
if [[ $# -ge 2 ]] && [[ $# -le 4 ]]; then
    num_options=0
    while getopts "qi" option; do
        case ${option} in
            q ) mode="quiet" ; num_options=$((num_options + 1)) ;;
            i ) keep_ids="false" ; num_options=$((num_options + 1)) ;;  # Sort of "insensitive [to IDs]"
            \? ) { usage >&2; exit 1; } ;;
        esac
    done

    pos_original=$((1 + num_options))
    pos_modified=$((2 + num_options))
    original="${@:pos_original:1}"
    modified="${@:pos_modified:1}"
# The number of arguments can only be two, three or four
else
    usage >&2
    exit 1
fi

# Options for the ./diff-nodes.sh and ./diff-edges.sh scripts
opt_mode=""
opt_keep_ids=""
[[ "$mode" == "quiet" ]] && opt_mode="-q"
[[ "$keep_ids" == "false" ]] && opt_keep_ids="-i"

# Comparing two .dot files with AGs
if [[ "${original##*.}" == "dot" ]] && [[ "${modified##*.}" == "dot" ]]; then
    # Check that both files exist
    ! [[ -f "$original" ]] && { echo "$0: file $original does not exist" >&2 ; exit 1 ; }
    ! [[ -f "$modified" ]] && { echo "$0: file $modified does not exist" >&2 ; exit 1 ; }

    # When running in quiet mode, report if the graphs are different or exit quietly if they are the same
    if [[ "$mode" == "quiet" ]]; then
        ./diff-nodes.sh $opt_mode $opt_keep_ids "$original" "$modified" 1> /dev/null && ./diff-edges.sh $opt_mode $opt_keep_ids "$original" "$modified" 1> /dev/null || { echo "Attack graphs $original and $modified are different" ; exit 1 ; }
    # When running in normal mode, show the common nodes and edges, and nodes and edges that are present in only one of the graphs (and their counts)
    else
        ./diff-nodes.sh $opt_mode $opt_keep_ids "$original" "$modified"
        echo "--------------------------------"
        ./diff-edges.sh $opt_mode $opt_keep_ids "$original" "$modified"
    fi
# Comparing two directories with .dot files with AGs
elif [[ -d "$original" ]] && [[ -d "$modified" ]]; then
    opt_mode="-q"
    # Check if the input directories exist
    original=$(echo "$original/" | tr -s '/')
    modified=$(echo "$modified/" | tr -s '/')
    ! [[ -d "$original" ]] && { echo "$0: directory $original does not exist" >&2 ; exit 1 ; }
    ! [[ -d "$modified" ]] && { echo "$0: directory $modified does not exist" >&2 ; exit 1 ; }

    # Resolve experiment names (i.e. remove the `AGs` part from the names of the directories)
    exp_original=$(echo "$original" | sed 's@AGs/@@')
    exp_modified=$(echo "$modified" | sed 's@AGs/@@')

    # This is the prefix used in every AG file name (ExpName-prefix-victim-mcatmserv)
    prefix="-attack-graph-for-victim-"

    # Actually compare the corresponding AGs in the input directories
    # First, find the AGs that are present in both directories (compare the file names without the experiment name and the prefix)
    failed="false"
    ags=$(comm -12 <(find "$original" -type f -name '*.dot' -printf '%f\n' | sed 's@'"${exp_original}\.txt${prefix}"'@@' | sort)\
             <(find "$modified" -type f -name '*.dot' -printf '%f\n' | sed 's@'"${exp_modified}\.txt${prefix}"'@@' | sort))

    # Exit with 1 if there is no overlap (i.e. if the directories are disjoint)
    [[ -z "$ags" ]] && exit 1

    # Recursively run the script on each pair of the matched attack graphs
    # For the attack graphs that are different, print "victim|mcat|mserv" instead of the default error message
    for ag in $(echo -e "$ags"); do
        sh -c "./diff-ags.sh $opt_mode $opt_keep_ids ${original}${exp_original}\.txt${prefix}$ag ${modified}${exp_modified}\.txt${prefix}$ag" |
          sed 's/^.*'"$prefix"'\(.*\)\.dot.*$/\1/' | sed 's/^\([0-9.]\+\)-/\1|/' | sed 's/\([A-Z]\+\)/\1|/' || failed="true"  # Check if the pipeline has failed
    done

    # Return the corresponding status code
    [[ "$failed" == "true" ]] && exit 1 || exit 0
else
   usage >&2
   exit 1
fi

